config/routes.rb
Rails.application.routes.draw do
  root to: 'blogs#index'
  resources :favorites, only: [:create, :destroy, :show]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title,   presence: true,
                        length: { maximum: 20 }
  validates :content, presence: true,
                        length: { maximum: 140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true,
                      length: { maximum: 20 }
  validates :email, presence: true,
                      length: { maximum: 255},
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  mount_uploader :selfpicture, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  #
  # def authenticate_user
  #   if @current_user == nil
  #     flash[:notice] = t('notice.login_needed')
  #     redirect_to new_session_path
  #   end
  # end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy,]
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @mailer = current_user
    if params[:back]
      render :new
    else
      if @blog.save
        BlogMailer.blog_mail(@mailer, @blog).deliver if @blog.image?
        redirect_to blogs_path, notice: "ブログ作成しました。"
      else
        render :new
      end
    end
  end

  def destroy
    if logged_in?
      @blog.destroy
      redirect_to blogs_path, notice: "ブログを削除しました"
    end
  end

  def show
    if logged_in?
      @blog
      @favorite = current_user.favorites.find_by(blog_id: @blog.id)
      @favorite_blogs = current_user.favorite_blogs
    end
  end

  def edit
    if logged_in?
    @blog
    end
  end

  def update
    @blog
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集されました"
    else
      render :edit
    end
  end


  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入りに登録しました。"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入りから解除しました。"
  end

  def show
    @favorite_blogs = current_user.favorite_blogs
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = "ログインに失敗しました"
        render :new
      end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to new_session_path
    else
    render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.present?
    @blog = Blog.where(user_id: current_user.id)
    @blog.destroy_all
    end
    @user.destroy
    redirect_to new_session_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :selfpicture, :selfpicture_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_blogs_path
    elsif action_name == "edit"
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, url: choose_new_or_edit, local: true) do | f | %>
  <% if @blog.errors.any? %>
    <div>
      <P><%= @blog.errors.count %>件のエラーがあります。</P>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
    <div>
      <div>
        <%= f.label :"タイトル:", class:"input-label"%>
      </div>
      <%= f.text_field :title, class:"input"%>
    </div>
    <div>
      <div>
        <%= f.label :"内容:", class:"input-label" %>
      </div>
      <%= f.text_area :content, class:"input blog-input" %>
    </div>
    <div>
      <%= f.label :"投稿画像", class:"input-label"%>
      <%= f.file_field :image, class:"input" %>
    </div>
    <div>
      <%= f.submit class:"input" %>
    </div>
    <div>
      <%= link_to "ブログ一覧へ戻る", blogs_path, class:"link"  %>
    </div>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<h1 class="title">投稿確認</h1>
<%= form_with(model: @blog, local: true, url: blogs_path) do | f | %>
  <div>
    <%= f.hidden_field :title %>
    <%= f.hidden_field :content %>
    <%= f.hidden_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="form-field">
    <div>
      <P>タイトル: </P>
    </div>
    <div>
      <p><%= @blog.title %></p>
    </div>
    <div>
      <P>内容:</P>
    </div>
    <div>
      <P><%= @blog.content %></P>
    </div>
    <div>
      <P><%= image_tag (@blog.image.url) if @blog.image && @blog.image.url %></P>
    </div>
    <div class="btn">
      <%= f.submit "この内容で投稿する" %>
    </div>
    <div class="btn">
      <%= f.submit "戻る", name: 'back' %>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1 class="title">ブログ編集</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1 class="title">ブログ一覧</h1>
<%= form_with(model: @blog, local: true) do | f | %>
  <%= notice %>
  <table>
    <tr>
      <th>タイトル</th>
      <th>投稿者</th>
      <th>投稿画像</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.user.name %></td>
        <td><%= image_tag blog.image.url if blog.image.url %></td>
          <td class="blog-content"><%= blog.content %></td>
          <td><%= link_to "詳細へ", blog_path(blog.id), class:"table-link" %></td>
          <% if logged_in? && blog.user_id == current_user.id%>
          <td><%= link_to "編集へ", edit_blog_path(blog.id), data:{ confirm: "編集しますか？"}, class:"table-link" %></td>
          <td><%= link_to "削除する", blog_path(blog.id), method: :delete, data:{ confirm: "削除しますか？"}, class:"table-link" %></td>
          <% end %>
      </tr>
    <% end %>
  </table>
  <div>
    <% if logged_in? %>
      <P class="link-p"><%= link_to "新規投稿へ", new_blog_path, class: "link" %></P>
    <% end %>
  </div>
<% end %>

app/views/blogs/new.html.erb
<h1 class="title">ブログ新規投稿</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1 class="title">ブログ詳細</h1>
<%= form_with(model:@blog, local: true ) do | f |%>
  <div class="form-field">
    <p>タイトル:</p>
    <div>
      <%= @blog.title %>
    </div>
    <p>内容:</p>
    <div>
      <%= @blog.content %>
    </div>
    <div>
      <%= image_tag @blog.image.url if @blog.image.url %>
    </div>
    <% if logged_in? %>
      <% unless @blog.user_id == current_user.id %>
        <% if @favorite.present? %>
          <div>
            <%= link_to "お気に入り解除する", favorite_path(id: @favorite.id), method: :delete, class: "btn btn-danger" %>
          </div>
        <% else %>
          <div>
            <%= link_to "お気に入りに追加する", favorites_path(blog_id: @blog.id), method: :post, class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <P class="link-p"><%= link_to "ブログ一覧へ戻る", blogs_path, class:"link" %></P>
  </div>
<% end %>

app/views/favorites/show.html.erb
<h1><%= current_user.name %> のお気に入り画像</h1>
<div>
  <% @favorite_blogs.each do |blog| %>
    <div>
      <%= image_tag blog.image.url %>
    </div>
    <div>
      <p>タイトル:  <%= blog.title %></p>
    </div>
  <% end %>
  <div>
    <%= link_to "ブログ一覧へ", blogs_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>INSklone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <header>
      <div class="header-logo">
        <h2>INSKlone</h2>
      </div>
      <div class="login">
        <% if logged_in? %>
        <%= link_to "マイページ", user_path(current_user.id), class:"header-link" %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class:"header-link" %>
        <% else %>
        <%= link_to "新規ユーザー登録", new_user_path, class:"header-link" %>
        <%= link_to "ログイン", new_session_path, class:"header-link" %>
        <% end %>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/users/_user_form.html.erb
<%= form_with(model: @user, local: true) do | f |%>
  <div class="error_explanation">
    <% if @user.errors.any? %>
      <p><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %>from being saved: </p>
      <ul>
        <% @user.errors.full_messages.each do | msg | %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="form-field">
    <div>
      <%= f.label :"お名前:", class:"input-label" %>
      <%= f.text_field :"name", class:"input"  %>
    </div>
    <div>
      <%= f.label :"Eメールアドレス:", class:"input-label"  %>
      <%= f.email_field :"email", class:"input"  %>
    </div>
    <div>
      <%= f.label :"パスワード:", class:"input-label"  %>
      <%= f.password_field :"password", class:"input"  %>
    </div>
    <div>
      <%= f.label :"パスワード確認:", class:"input-label"  %>
      <%= f.password_field :"password_confirmation", class:"input"  %>
    </div>
    <div>
      <%= f.label :"プロフィール写真", class:"input-label" %>
      <%= f.file_field "selfpicture", class:"input"  %>
    </div>
    <div>
      <%= f.submit "登録をする", class:"input"%>
    </div>
    <div>
      <%= link_to "ブログ一覧へ", blogs_path, class:"link"  %>
    </div>
  </div>


<% end %>

app/views/users/edit.html.erb
<h1 class="title">ユーザー登録編集</h1>
<%= render 'user_form'%>

app/views/users/new.html.erb
<h1 class="title">新規ユーザー登録</h1>
<%= render 'user_form'%>

app/views/users/show.html.erb
<h1 class="title"><%= @user.name %> ページ</h1>
<div class="form-field">
  <P>お名前: <%= @user.name %> </P>
  <P>Eメールアドレス: <%= @user.email %></P>
  <div>
    <p>ブロフィール写真</p>
      <%= image_tag @user.selfpicture.url if @user.selfpicture.url%>
  </div>
  <div class="link-margin">
    <%= link_to "お気に入り画像ページへ", favorite_path(current_user.id), class:"link" if logged_in?%>
  </div>
  <div class="link-margin">
    <%= link_to "登録情報を編集する", edit_user_path(current_user.id), data:{confirm: "登録を編集してもいいですか？"}, class:"link" if logged_in? %>
  </div>
  <div class="link-margin">
    <%= link_to "新規ブログ投稿へ", new_blog_path, class:"link" %>
  </div>
  <div class="link-margin">
    <%= link_to "ブログ一覧へ", blogs_path, class:"link" %>
  </div>
  <div class="link-margin">
    <%= link_to "【注意！】ユーザー登録を削除する", user_path, method: :delete, data:{confirm: "(重要)本当にユーザー登録を消してもいいですか!!?"}, class:"link"%>
  </div>
</div>